---
image: python

stages:
  - test
  - build
  - release

before_script:
  - apt update

cache:
  paths:
    - .venv

style:
  image: python:3.11
  stage: test
  script:
    - pip install pre-commit
    - pre-commit run --all-files --show-diff-on-failure

python38:
  image: python:3.8
  stage: test
  script:
    - poetry install --extras all
    - poetry run pytest

python39:
  image: python:3.9
  stage: test
  script:
    - poetry install --extras all
    - poetry run pytest

python310:
  image: python:3.10
  stage: test
  script:
    - poetry install --extras all
    - poetry run pytest

python311:
  image: python:3.11
  stage: test
  script:
    - poetry install --extras all
    - poetry run pytest

minversions:
  image: python:3.8
  stage: test
  script:
    - sed -i -E 's/"(\^|>=)([0-9\.]+)(.*)"/"==\2"/' pyproject.toml
    - sed -i -E 's/python = "==/python = "^/' pyproject.toml
    - poetry lock
    - poetry install --extras all
    - poetry run pytest

doc:
  image: python:3.11
  stage: test
  script:
    - poetry install --only doc
    - poetry run sphinx-build doc build/sphinx/html
