---
version: 2
sphinx:
  configuration: doc/conf.py
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry export --with doc --output requirements.txt
    post_install:
      - pip install .
      - pip install --requirement requirements.txt
